Update to support PHP 8.1
laminas/laminas-serializer pull request #13
Opened 2021-10-21 09:32 UTC by pascalheidmann

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

With this PR [`laminas/laminas-serializer`](https://github.com/laminas/laminas-serializer) runs under PHP 8.1.
It updates several dependencies to allow compatibility especially with [`laminas/laminas-coding-style`](https://github.com/laminas/laminas-coding-style). This results in quite a few changes code style improvements and better code quality.

~As this PR also adds return types & type hints to several classes this might be considered as a breaking change. Those changes are also listed in the newly added `CHANGELOG.md`.~
BCs like return types & type hints for library sources are not part anymore (I left those in tests as those shouldn't be a concern of changes of signatures).

2021-10-21 09:37 UTC, Ocramius requested changes

2021-10-21 09:37 UTC, Ocramius commented on src/AbstractSerializer.php
> +abstract class AbstractSerializer
This is a major BC break: we can't really introduce this for a dependency upgrade :thinking:

2021-10-21 09:37 UTC, Ocramius commented on src/Adapter/JsonOptions.php
> +    public function setCycleCheck(bool $flag): self
We can't add return types on non-`final` classes, as it is a BC break

2021-10-21 09:37 UTC, Ocramius commented on src/Adapter/JsonOptions.php
> +    public function setCycleCheck(bool $flag): self
Adding parameter type declarations is a bit milder as a BC break, but still a major problem: before, we would use a type cast, and now users get a crash.

Can't be done here.

2021-10-21 09:37 UTC, Ocramius commented on src/Adapter/PythonPickle.php
> +    private const OP_MARK            = '(';     // push special markobject on stack
These constants were implicitly `public` before - we can't make them `private` here, as it is a BC break.

2021-10-21 10:07 UTC, froschdesign commented
@pascalheidmann 
Thank you for your contribution!

[This package is security-only maintenance mode](https://github.com/laminas/laminas-serializer#readme) therefore the support for PHP 8.1 is good, but any breaking changes must be omitted.
Thanks in advance! 👍

2021-10-21 13:41 UTC, Ocramius requested changes

2021-10-21 13:41 UTC, Ocramius commented on composer.lock
> -{
I see `composer.lock` was completely deleted: we should really have it at its original state, if possible.

See how upgrades were done elsewhere, such as in https://github.com/laminas/laminas-diactoros/pull/70, which uses a `.laminas-ci.json` to make CI run also when deps are locked

2021-10-21 13:41 UTC, Ocramius commented on src/Adapter/PhpSerialize.php
> +                $value = $value::class;
`$value::class` won't work on PHP 7.3, I think?

2021-10-21 13:41 UTC, Ocramius commented on src/Adapter/PythonPickle.php
> +        [, $id] = unpack('l', $bin);
Does the `[, $id] = ` syntax also work on 7.3?

2021-10-21 13:41 UTC, Ocramius commented on src/AdapterPluginManager.php
> +                is_object($instance) ? $instance::class : gettype($instance)
Similar to above, `::class` is fairly new on variables

2021-10-22 07:42 UTC, driehle commented on src/Adapter/PhpSerialize.php
> +                $value = $value::class;
That was introduced in PHP 8.0 (https://3v4l.org/qVnSI).

2021-10-22 07:44 UTC, driehle commented on src/Adapter/PythonPickle.php
> +        [, $id] = unpack('l', $bin);
This should be fine, seems it has been introduced in PHP 7.1 (https://3v4l.org/8qrE6).

2021-10-23 19:03 UTC, Ocramius commented on src/AdapterPluginManager.php
> +        wddx::class         => Adapter\Wddx::class,
Casing seems to have broken here? 🤔

2021-10-23 20:38 UTC, pascalheidmann commented on src/AdapterPluginManager.php
> +        wddx::class         => Adapter\Wddx::class,
Well, looks like you are right and `phpcs` has some bug there (auto-import happened by `phpcs`/`phpbf`) :/
Will fix it & have also a look at `phpcs`'s fix for this behavior 🤔

2021-10-24 10:52 UTC, Ocramius approved these changes
LGTM, thanks @pascalheidmann!

2021-10-24 10:53 UTC, merged