Add support for `laminas-servicemanager` v4.0
laminas/laminas-serializer pull request #25
Opened 2023-07-02 16:45 UTC by boesing

|    Q          |   A
|-------------- | ------
| BC Break      | yes
| New Feature   | yes

### Description

This provides support for `laminas-servicemanager` v4.0

2023-07-02 16:48 UTC, boesing commented on composer.json
> +        "php": "~8.1.0 || ~8.2.0",
`laminas-servicemanager` dropped support for PHP 8.0 and thus we can drop it here as well.

2023-07-03 08:16 UTC, Ocramius requested changes

2023-07-03 08:16 UTC, Ocramius commented on composer.json
> +        "laminas/laminas-servicemanager": "^4.0.0-rc2",
title says "add support", but implementation adds it as a requirement (wasn't one before, BTW). 

Not sure what the right direction is here :thinking:

2023-07-03 08:31 UTC, boesing commented on composer.json
> +        "laminas/laminas-servicemanager": "^4.0.0-rc2",
AFAIR we decided on stating explicit requirements in components to avoid surprises in upstream projects.

The `AdapterPluginManager` and the `Serializer` abstract class are totally depending on the `AdapterPluginManager`. So the only things which are not servicemanager related are the concrete implementations.

Not sure if we should extract the plugin manager specific code to a satellite instead but having 60+% of this component being dangling until composer requirements are fulfilled feels weird to me.

2023-07-03 09:49 UTC, Ocramius commented on composer.json
> +        "laminas/laminas-servicemanager": "^4.0.0-rc2",
Works for me :+1:

2023-07-03 09:49 UTC, Ocramius approved these changes

2023-07-07 21:49 UTC, merged