Added support for "serializers" from config in AdapterPluginManager
laminas/laminas-serializer pull request #8
Opened 2021-01-01 11:29 UTC by marc-jangvs

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

Added support to load the registered Serializers from the `serializers` config key. Currently this is only supported in `Module.php` when using Laminas MVC. 

Changed this to the format as in other components are build such as the `FilterPluginManagerFactory` in `laminas/laminas-log`.

Change is fully backwards compatible and now more in line with the other Laminas components.

2021-01-01 14:58 UTC, Ocramius approved these changes
IMO the idea is OK, but I don't have an overview on whether this is what is wished for when moving forward with the component. Perhaps either @Xerkus or @weierophinney can give more insight on this.

TODOs:

 1. [ ] we really need documentation for this new configuration approach
 2. [ ] to be rebased to remove @michalbundyra's commit from the PR

2021-01-02 18:13 UTC, marc-jangvs commented
@Ocramius just rebased so only my own commits are in this PR.

What are your expectations of the documentations? Shall I write something like the documentation of the PluginManager of `laminas-hydrator` (https://github.com/laminas/laminas-hydrator/blob/4.2.x/docs/book/v4/plugin-managers.md)?

2021-01-05 21:45 UTC, weierophinney commented
> What are your expectations of the documentations? Shall I write something like the documentation of the PluginManager of `laminas-hydrator` (https://github.com/laminas/laminas-hydrator/blob/4.2.x/docs/book/v4/plugin-managers.md)?

Yes, exactly. Make sure you add the file to the `mkdocs.yml` so that it will build and show up in the TOC as well.

Otherwise, this looks good!

2021-01-09 15:27 UTC, marc-jangvs commented
> > What are your expectations of the documentations? Shall I write something like the documentation of the PluginManager of `laminas-hydrator` (https://github.com/laminas/laminas-hydrator/blob/4.2.x/docs/book/v4/plugin-managers.md)?
> 
> Yes, exactly. Make sure you add the file to the `mkdocs.yml` so that it will build and show up in the TOC as well.
> 
> Otherwise, this looks good!

Great, just added a plugin-manager.md with the same kind of documentation as in the hydrator package.

2021-01-11 12:50 UTC, froschdesign commented on docs/book/plugin-manager.md
> +
An introduction is missing to what the manager can be used for.

2021-01-11 13:08 UTC, froschdesign requested changes
Some updates for documentation are needed. Thanks in advance! 👍

2021-01-11 13:08 UTC, froschdesign commented on docs/book/plugin-manager.md
> +`Laminas\Serializer\AdapterPluginManager` is mapped to the factory
Please also add the information that the factory is registered in a laminas-mvc based application during installation.

2021-02-17 17:06 UTC, weierophinney commented
Rebased against 2.10.x and merged with 1c57f1b.

2021-02-17 17:06 UTC, closed without merging